version: '3'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5444:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: course
      POSTGRES_PASSWORD: password
      POSTGRES_DB: course
